import { useEffect, useRef } from 'react';
import { Crepe } from '@milkdown/crepe';
import '@milkdown/crepe/theme/common/style.css';
import '@milkdown/crepe/theme/nord.css';

import {
  milkdownAIUtils,
  createAISlashMenuConfig,
  createAIToolbarConfig
} from '../plugins/ai';
import AIModal, { AIOption } from '../plugins/ai/ui/AIModal';
import { useAIModal } from '../plugins/ai/hooks/useAIModal';
import { toast } from '@/hooks/use-toast';

const TestPlate = () => {
  const editorRef = useRef<HTMLDivElement>(null);
  const crepeRef = useRef<Crepe | null>(null);
  const aiModal = useAIModal();

  // AI Modal handlers - wrapped in useRef to avoid recreating on every render
  const handleToolbarAIClick = useRef(() => {
    // Don't get selected text here - context not available yet
    // We'll get it when AI executes
    aiModal.openModal('toolbar', '');
  });

  const handleSlashMenuAIClick = useRef(() => {
    aiModal.openModal('slash-menu');
  });

  const handleAIExecute = async (option: AIOption | null, customPrompt?: string) => {
    try {
      // Check if editor is ready
      if (!milkdownAIUtils.isReady()) {
        throw new Error('Editor is not ready. Please wait a moment and try again.');
      }

      // Get selected text NOW when context is available (not in the click handler)
      const selectedText = aiModal.context === 'toolbar' ? milkdownAIUtils.getSelectedText() : '';

      // Construct the proper prompt based on option and context
      let prompt: string;

      if (option) {
        // Predefined option selected
        if (aiModal.context === 'toolbar' && selectedText) {
          // Use selected text as context for the task
          prompt = `${option.label} the following text:\n\n${selectedText}`;
        } else {
          // No selected text, use general context
          prompt = `${option.label} in the context of the current document`;
        }
      } else if (customPrompt) {
        // Custom prompt entered
        if (aiModal.context === 'toolbar' && selectedText) {
          // Add selected text as context
          prompt = `${customPrompt}\n\nContext (selected text):\n${selectedText}`;
        } else {
          // Use custom prompt as-is
          prompt = customPrompt;
        }
      } else {
        throw new Error('No option or prompt provided');
      }

      // Call existing backend LLM service directly - no duplicate service layer
      const response = await fetch('/api/llm/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify({
          prompt: prompt.trim(),
          temperature: 0.7,
          preferFree: true, // Uses existing provider priority logic
        }),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const result = await response.json();

      if (!result.success || !result.data?.content) {
        throw new Error(result.error?.message || 'Failed to generate content');
      }

      // Double-check editor is still ready before inserting
      if (!milkdownAIUtils.isReady()) {
        throw new Error('Editor lost focus. Please try again.');
      }

      // Insert result into editor based on context
      // Note: Crepe doesn't support direct text manipulation, so AI operations will show a message
      if (aiModal.context === 'toolbar' && selectedText) {
        // Replace selected text
        const success = milkdownAIUtils.replaceSelectedText(result.data.content);
        if (!success) {
          throw new Error('AI text replacement is not supported with Crepe editor. This is a limitation of Crepe\'s design.');
        }
      } else {
        // Insert at cursor
        const success = milkdownAIUtils.insertAtCursor(result.data.content);
        if (!success) {
          throw new Error('AI text insertion is not supported with Crepe editor. This is a limitation of Crepe\'s design.');
        }
      }

      toast({
        title: "AI completed!",
        description: `Generated by ${result.data.providerName} in ${result.data.responseTime}ms`,
      });
    } catch (error) {
      console.error('AI execution error:', error);
      toast({
        title: "AI Error",
        description: error instanceof Error ? error.message : "Failed to process request",
        variant: "destructive"
      });
      throw error; // Re-throw to let modal handle loading state
    }
  };

  useEffect(() => {
    if (!editorRef.current) return;

    const crepe = new Crepe({
      root: editorRef.current,
      defaultValue: `# Welcome to Milkdown Editor

This is a powerful **markdown editor** with a beautiful interface.

## Features

- 📝 **Rich Markdown Support** - Write in markdown with live preview
- 🎨 **Beautiful Theme** - Modern, clean interface
- ⚡ **Fast & Lightweight** - Built with ProseMirror
- 🤖 **AI Assistant** - Powered by your existing LLM infrastructure

## Try It Out

Type **/** to open the command menu and explore available options.

Select text and click the AI button in the toolbar to modify it with AI.

> 💡 **Tip**: You can use standard markdown syntax like **bold**, *italic*, \`code\`, and more!

Start writing below...
      `,
      featureConfigs: {
        [Crepe.Feature.BlockEdit]: createAISlashMenuConfig(handleSlashMenuAIClick.current),
        [Crepe.Feature.Toolbar]: createAIToolbarConfig(handleToolbarAIClick.current),
      },
    });

    crepe.create().then(() => {
      console.log('Milkdown editor created successfully');
      crepeRef.current = crepe;

      // Initialize AI utilities with the crepe instance
      milkdownAIUtils.setCrepe(crepe);
    }).catch((error) => {
      console.error('Failed to create editor:', error);
    });

    return () => {
      if (crepeRef.current) {
        crepeRef.current.destroy();
        crepeRef.current = null;
      }
    };
  }, []);

  return (
    <div className="container mx-auto p-8 max-w-5xl">
      <div className="mb-6">
        <h1 className="text-3xl font-bold mb-2">Milkdown Editor</h1>
        <p className="text-muted-foreground">
          A powerful markdown editor with a beautiful interface. Type <kbd className="px-2 py-1 text-xs bg-muted rounded">/</kbd> to open the command menu.
        </p>
      </div>

      <div className="border rounded-lg bg-card shadow-sm overflow-hidden">
        <div
          ref={editorRef}
          className="min-h-[500px] milkdown-editor-wrapper"
        />
      </div>

      <div className="mt-6 p-4 bg-muted rounded-lg">
        <h3 className="font-semibold mb-2">Features:</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div>
            <p className="font-medium mb-1">Editor:</p>
            <ul className="space-y-1">
              <li>📝 Full markdown support</li>
              <li>🎨 Beautiful WYSIWYG interface</li>
              <li>⚡ Real-time preview</li>
              <li>⌨️ Keyboard shortcuts</li>
            </ul>
          </div>
          <div>
            <p className="font-medium mb-1">Commands:</p>
            <ul className="space-y-1">
              <li>📄 Headings and paragraphs</li>
              <li>• Lists and checklists</li>
              <li>📊 Tables and quotes</li>
              <li>🔗 Links and images</li>
            </ul>
          </div>
        </div>
        <div className="mt-4 p-3 bg-background rounded border">
          <p className="text-xs font-medium mb-2">💡 Pro Tips:</p>
          <ul className="text-xs space-y-1 text-muted-foreground">
            <li>• Type <kbd className="px-1 py-0.5 bg-muted rounded">/</kbd> to access all commands</li>
            <li>• Use <kbd className="px-1 py-0.5 bg-muted rounded">**text**</kbd> for bold and <kbd className="px-1 py-0.5 bg-muted rounded">*text*</kbd> for italic</li>
            <li>• Press <kbd className="px-1 py-0.5 bg-muted rounded">Ctrl+Z</kbd> to undo changes</li>
            <li>• Drag and drop images directly into the editor</li>
          </ul>
        </div>
        <p className="text-xs text-muted-foreground mt-3">
          Built with Milkdown - A modern WYSIWYG markdown editor
        </p>
      </div>

      {/* AI Modal */}
      <AIModal
        isOpen={aiModal.isOpen}
        onClose={aiModal.closeModal}
        context={aiModal.context}
        selectedText={aiModal.selectedText}
        onExecuteAI={handleAIExecute}
      />
    </div>
  );
};

export default TestPlate;
